# Copyright 2013,2014 PTFS Europe Ltd
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# Koha is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with Koha; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# This file creates a data structure defining valid item types and
# their fields for the British Library DSS InterLibrary Loan API.
#
# The first section defines fields for the various request field
# levels. For the BL API, each request can have information at the
# title, Item and Item of Interest levels.
#
# The second section defines the BL DSS API item types, and defines
# which of the fields defined in the first section are relevant for
# this item type.

# The 'record' data structure provides an overview of the xml records
# we are interested in receiving.  This structure is an abstract
# representation of the XML we receive from the API at the individual
# record level of the search results.

# The semantics of our abstract representation are as follows:
# - The top level is always called 'record' — we are working at the
#   record level in a set of results returned by an API.
# - Each element we want to refer to in the API's record response
#   should be a key at record's next level of indentation.
# - We recognise 4 keywords to 'mark-up' our representation;
#   + name: a human readable value for the field. This is used, for
#     instance, for rendering the field's value on webpages. Any
#     fields that have a 'name' keyword are returned as part of the
#     'getFullDetails' method of ILL Records.
#   + inSummary: if used for a field, then this field will be one of
#     the fields returned by the 'getSummary' method of ILL Records.
#   + accessor: if defined, this is the id that can be used in the
#     'getProperty' method of ILL Records.
#   + go: if go is defined then our ILL parser will ignore this field
#     level, and instead process each child of this level.
#
# Remember: to simply not work with given fields returned by the API's
# response it suffices to not define those fields in the abstract
# representation at all.

record:
  uin:
    name: British Library Identifier
    inSummary: True
    accessor: title
  type:
    name: Material Type
    inSummary: True
  isAvailableImmediateley:
    name: Available now?
  metadata:
    go: True
    titleLevel:
      go: True
      title:
        name: Title
        inSummary: True
      author:
        name: Author
        inSummary: True
      identifier:
        name: Identifier
      publisher:
        name: Publisher
        inSummary: True
      issn:
        name: ISSN
        inSummary: True
      isbn:
        name: ISBN
        inSummary: True
      ismn:
        name: ISMN
      shelfmark:
        name: Shelfmark
      conferenceVenue:
        name: Conference Venue
      conferenceDate:
        name: Conference Date
      thesisUniversity:
        name: Thesis University
      thesisDissertation:
        name: Thesis Dissertation
      mapScale:
        name: Map Scale
    itemLevel:
      go: True
      year:
        name: Year
        inSummary: True
      volume:
        name: Volume Number
      issue:
        name: Issue Number
      part:
        name: Part Number
      edition:
        name: Edition
        inSummary: True
      season:
        name: Season
      month:
        name: Month
      day:
        name: Day
      specialIssue:
        name: Special Issue
    itemOfInterestLevel:
      go: True
      title:
        name: Title
      author:
        name: Author
      pages:
        name: Pages

availability:
  loanAvailabilityDate:
    name: Loan availability date
    inSummary: True
  copyAvailabilityDate:
    name: Copy availability date
    inSummary: True
  copyrightFee:
    name: Copyright fee
    inSummary: True
  availableImmediately:
    name: Available immediately?
    inSummary: True
  matchedToSpecificItem:
    name: Matched to specific item?
    inSummary: True
  isOnOrder:
    name: On order?
    inSummary: True
  availableFormats:
    go: True
    availableFormat:
      go: True
      deliveryFormat:
        name: Delivery format
        inSummary: True
      deliveryModifiers:
        name: Delivery modifiers
        inSummary: True
      availableSpeeds_speed:
        name: Speed
        inSummary: True
